
MKDIR_P = mkdir -p
LN_S = ln -s

COMPILE_MODE := SHARED

BUILDDIR := $(PROJECTDIR)/build

OBJDIR := $(BUILDDIR)/$(SUBDIR)
LIBDIR := $(BUILDDIR)
BINDIR := $(BUILDDIR)

AR = ar
ARFLAGS = c
CC = clang
CFLAGS = -O3 -Wall -I$(PROJECTDIR) -DSUBDIR=\"$(SUBDIR)\" #-DNO_LOG -DNO_ASSERT -DNO_PRECOND -DNO_ERROR
CFLAGS_OBJ_SHARED = $(CFLAGS) -c -fPIC
CFLAGS_OBJ_STATIC = $(CFLAGS) -c
CFLAGS_OBJ = $(CFLAGS_OBJ_$(COMPILE_MODE))

LDFLAGS = -L$(LIBDIR)
LDFLAGS_LIB = $(LDFLAGS) -shared -O4
LDFLAGS_BIN = $(LDFLAGS)

LIB_SUFFIX_SHARED = .so
LIB_SUFFIX_STATIC = .a
LIB_SUFFIX = $(LIB_SUFFIX_$(COMPILE_MODE))
BIN_SUFFIX =

DRIVERS=applemidi

