#include "applemidi.h"

#define APPLEMIDI_PROTOCOL_SIGNATURE          0xffff

#define APPLEMIDI_COMMAND_INVITATION          0x494e /** "IN" */
#define APPLEMIDI_COMMAND_INVITATION_REJECTED 0x4e4f /** "NO" */
#define APPLEMIDI_COMMAND_INVITATION_ACCEPTED 0x4f4b /** "OK" */
#define APPLEMIDI_COMMAND_ENDSESSION          0x4259 /** "BY" */
#define APPLEMIDI_COMMAND_SYNCHRONIZATION     0x434b /** "CK" */
#define APPLEMIDI_COMMAND_RECEIVER_FEEDBACK   0x5253 /** "RS" */
